### ISSUE TITLE
Usage example in the README is incorrect

### ISSUE THREAD

**Issue by sumdog** [itafroma/jekyll-post_groups#5]
Is this plugin broken on Jekyll 2.5.3?

I have something like the following from the example:
```
{% for section in site.ser %}
<section>
    <h1>{{ section | first }}</h1>
    {% for post in section %}
    <article>
        <h1>--{{ post }}--</h1>
    </article>
    {% endfor %}
</section>
{% endfor %}
```
With my config looking like the following:
```
post_groups:
    - key: series
      group: ser
```

Where you see the `--{{ post }}--` I first attempted a `post.title` and got nothing. I tried many other attributes and the only thing that works is post by itself, but it globs everything together; every post in that section as one big string. I can't tell if it has any attributes because Liquid templates have no means of debugging variables (without writing your own plugin).

I'm just wondering is something changed that's breaking this plugin. I see the section headings, but I can get the individual attributes out of the posts.

**Comment by itafroma** [comment]
There isn't anything broken specifically due to 2.5.3 (or at all, that I'm aware of, at least): [my own website](https://github.com/itafroma/marktrapp.com) uses Jekyll 2.5.3 successfully with jekyll-post_groups 0.2.0:

* [My Gemfile.lock](https://github.com/itafroma/marktrapp.com/blob/production/Gemfile.lock)
* [Example of my usage](https://github.com/itafroma/marktrapp.com/blob/production/jekyll/blog/index.html) (also [here](https://github.com/itafroma/marktrapp.com/blob/production/jekyll/_includes/archive_section_blog.html))

Your snippets look sane so I'm not sure what would be going wrong for you based on them and can only suggest some basic troubleshooting steps:

* Have you tried downgrading and testing 2.5.2 or even 2.4.* to eliminate Jekyll as the problem?
* Are you running jekyll-post_groups 0.2.0?
* Are you running any other plugins that might be interfering at that stage?

**Comment by sumdog** [comment]
So I just got started using Jekyll; trying to convert a legacy/proprietary site of mine. I did a fresh 'gem install jekyll' as a regular user. In my `~/.gem/ruby/1.9.1/gems` I have a `jekyll-itafroma-post_groups-0.2.0`. No Gemfile.lock for my project yet.

So some more details: if I have some files in `_post` that looks like the following:

```
title: Some story
layout: post
permalink: /story/chapter1/some-story
date: 2004-06-11
categories:
  - story
tags:
  - some
  - tags
section: Chapter 1
```

And then I have a page at my root called `stories.html` that looks like the following:

```
---
title: Stories
layout: page
permalink: /stories/
---
{% for section in site.sections %}
<section>
    <p>0--{{ section[0] }}</p>
    <p>1--{{ section[1] }}</p>
    <p>2--{{ section[2] }}</p>
    {% for post in section %}
    <article>
        <p>P0--{{ post[0] }}</p>
        <p>P1--{{ post[1] }}</p>
    </article>
    {% endfor %}
</section>
{% endfor %}
```

For the output of this page I get:
0 -- Chapter 1
1 -- The body for every post in that section concatenated together (latest first)
2 -- empty string

And I never get P0-- or P1--, so the `post in section` seems to be an empty set.

**Comment by sumdog** [comment]
After some more fiddling, I got the following to work correctly:

```
{% for section in site.sections %}
    <span class="serise">{{ section[0] }}</span>
    {% for post in section[1] reversed %}
       <span class="dtime">( {{ post.tags | join:' ' }} )  ({{ post.date | date: "%Y-%m-%d" }})</span>
       <span class="listlink">
         <a href="{{ post.url }}">{{ post.title }}</a>
       </span>
    {% endfor %}
{% endfor %}
```
Is there a non-numeric key to get the section name (section[0])? I ask because I'd also like to sort the sections alphabetically, possibly by using something like the [sorted_for  plugin](https://gist.github.com/mbland/3812259)? (or is there a better way to sort them?)

**Comment by itafroma** [comment]
Glad you were able to make it work! Now that I see it, the usage example in the README was wrong and shouldn't work. I've updated the README to reflect the correct usage.

It works this way because Jekyll's own API for accessing the built-in post groups it provides (`site.categories` and `site.tags`) works this way, and they in turn work that way because Liquid's ability to handle hashes and arrays is pretty awful.

So `site.sections` (and `site.tags` and `site.categories`) is actually defined as a hash. Something like this JSON representation:

``` json
{
    "Section1": [
        {
            "title": "Post1"
        },
        {
            "title": "Post2"
        },
        {
            "title": "Post3"
        }
    ],
    "Section2": [
        {
            "title": "Post1"
        },
        {
            "title": "Post2"
        },
        {
            "title": "Post3"
        }
    ]
}
```

In Ruby, if you wanted to iterate over that, you'd do something like:

``` ruby
sections.each do |name, posts|
end
```

Or in PHP:

``` php
foreach ($sections as $name => $posts) {
}
```

There is no such construct in Liquid, however: just the normal `{% for %}` block. So when Liquid sees it's iterating over a hash, [it does something unintuitive](https://github.com/Shopify/liquid/wiki/Liquid-for-Designers#for-loops): it effectively creates a new wrapping array over each of the hash elements. So when you do:

``` liquid
{% for section in site.sections %}
{% endfor %}
```

Liquid puts the hash key in `section[0]` and the hash value in `section[1]`. You can use `{{ section | first }}` instead of `{{ section[0] }}` to get the section name if you'd like, but it's really six of one, half-dozen of the other.

I don't have any experience with the sorted_for plugin, but that quirk of Liquid is something you'll probably have to deal with either way. With all that above taken into account, this is how I wind up sort sections on [my blog listing page](https://marktrapp.com/blog):

``` liquid
{% for section in site.sections %}
    {% assign section_names = section_names | append: section[0] | append: '||' %}
{% endfor %}
{% assign section_names_sorted = section_names | split: '||' | sort %}


{% for section_name in section_names_sorted %}
<section>
    <h1 id="{{ section_name | escape }}">{{ section_name }}</h1>
    {% for post in site.sections[section_name] %}
    <article>
        <h1><a href="{{post.url}}">{{ post.title }}</a></h1>
        {{ post.excerpt }}
    </article>
    {% endfor %}
</section>
{% endfor %}
```

In addition to having poor hash support, Liquid's array creation abilities are very limited: you can't create your own arrays, you can only get new arrays if a filter returns one. So the above demonstrates a workaround: first, concatenate all the section names with a delimiter. Then, use Liquid's
split filter to create the array. Once you have an array, then you can sort it.

**Comment by sumdog** [comment]
Thanks @itafroma. I ended up learning all about hashes and liquid templates. I ended needing too much custom stuff and rolled my own plugin and did all the sorting within it. Here a tip I found; if you want to pass a hash from a plugin back to liquid, you can do the following: 

```
context.registers[:page]['your_variable'] = @your_hash
```

You still have to do the `for i in pages.your_variable` and `i[0]` thing inside the liquid template. 

I was going to add an update to your docs and send a pull request, but I can see you've already taken care of it. Also, Liquid templates are quite frustrating :-P
